export const AGREGAR_CATEGORIA ='AGREGAR_CATEGORIA';
export const AGREGAR_CATEGORIA_EXITO ='AGREGAR_CATEGORIA_EXITO';
export const AGREGAR_CATEGORIA_ERROR ='AGREGAR_CATEGORIA_ERROR';

export const COMENZAR_DESCARGA_CATEGORIAS = 'COMENZAR_DESCARGA_CATEGORIAS';
export const DESCARGA_CATEGORIAS_EXITO = 'DESCARGA_CATEGORIAS_EXITO';
export const DESCARGA_CATEGORIAS_ERROR = 'DESCARGA_CATEGORIAS_ERROR';

export const OBTENER_CATEGORIA_ELIMINAR = 'OBTENER_CATEGORIA_ELIMINAR';
export const CATEGORIA_ELIMINADA_EXITO = 'OBTENER_CATEGORIA_ELIMINADA_EXITO';
export const CATEGORIA_ELIMINADA_ERROR = 'OBTENER_CATEGORIA_ELIMINADA_ERROR';

export const OBTENER_CATEGORIA_ACTUALIZAR = 'OBTENER_CATEGORIA_ACTUALIZAR';
export const COMENZAR_ACTUALIZACION_CATEGORIA = 'COMENZAR_ACTUALIZACION_CATEGORIA';
export const CATEGORIA_ACTUALIZADA_EXITO = 'OBTENER_CATEGORIA_ACTUALIZADA_EXITO';
export const CATEGORIA_ACTUALIZADA_ERROR = 'OBTENER_CATEGORIA_ACTUALIZADA_ERROR';

export const AGREGAR_PERSONA ='AGREGAR_PERSONA';
export const AGREGAR_PERSONA_EXITO ='AGREGAR_PERSONA_EXITO';
export const AGREGAR_PERSONA_ERROR ='AGREGAR_PERSONA_ERROR';

export const COMENZAR_DESCARGA_PERSONAS = 'COMENZAR_DESCARGA_PERSONAS';
export const DESCARGA_PERSONAS_EXITO = 'DESCARGA_PERSONAS_EXITO';
export const DESCARGA_PERSONAS_ERROR = 'DESCARGA_PERSONAS_ERROR';

export const OBTENER_PERSONA_ELIMINAR = 'OBTENER_PERSONA_ELIMINAR';
export const PERSONA_ELIMINADA_EXITO = 'OBTENER_PERSONA_ELIMINADA_EXITO';
export const PERSONA_ELIMINADA_ERROR = 'OBTENER_PERSONA_ELIMINADA_ERROR';

export const OBTENER_PERSONA_ACTUALIZAR = 'OBTENER_PERSONA_ACTUALIZAR';
export const COMENZAR_ACTUALIZACION_PERSONA = 'COMENZAR_ACTUALIZACION_PERSONA';
export const PERSONA_ACTUALIZADA_EXITO = 'OBTENER_PERSONA_ACTUALIZADA_EXITO';
export const PERSONA_ACTUALIZADA_ERROR = 'OBTENER_PERSONA_ACTUALIZADA_ERROR';
export const COMENZAR_DESCARGA_PERSONA = 'COMENZAR_DESCARGA_PERSONA';

export const AGREGAR_LIBRO ='AGREGAR_LIBRO';
export const AGREGAR_LIBRO_EXITO ='AGREGAR_LIBRO_EXITO';
export const AGREGAR_LIBRO_ERROR ='AGREGAR_LIBRO_ERROR';

export const COMENZAR_DESCARGA_LIBROS = 'COMENZAR_DESCARGA_LIBROS';
export const DESCARGA_LIBROS_EXITO = 'DESCARGA_LIBROS_EXITO';
export const DESCARGA_LIBROS_ERROR = 'DESCARGA_LIBROS_ERROR';

export const OBTENER_LIBRO_ELIMINAR = 'OBTENER_LIBRO_ELIMINAR';
export const LIBRO_ELIMINADO_EXITO = 'OBTENER_LIBRO_ELIMINADO_EXITO';
export const LIBRO_ELIMINADO_ERROR = 'OBTENER_LIBRO_ELIMINADO_ERROR';

export const OBTENER_LIBRO_ACTUALIZAR = 'OBTENER_LIBRO_ACTUALIZAR';
export const COMENZAR_ACTUALIZACION_LIBRO = 'COMENZAR_ACTUALIZACION_LIBRO';
export const LIBRO_ACTUALIZADO_EXITO = 'OBTENER_LIBRO_ACTUALIZADO_EXITO';
export const LIBRO_ACTUALIZADO_ERROR = 'OBTENER_LIBRO_ACTUALIZADO_ERROR';

export const OBTENER_LIBRO_PRESTAR = 'OBTENER_LIBRO_PRESTAR';
export const COMENZAR_PRESTAR_LIBRO = 'COMENZAR_PRESTAR_LIBRO';
export const LIBRO_PRESTAR_EXITO = 'OBTENER_LIBRO_PRESTAR_EXITO';
export const LIBRO_PRESTAR_ERROR = 'OBTENER_LIBRO_PRESTAR_ERROR';

export const OBTENER_LIBRO_DEVOLVER = 'OBTENER_LIBRO_DEVOLVER';
export const COMENZAR_DEVOLVER_LIBRO = 'COMENZAR_DEVOLVER_LIBRO';
export const LIBRO_DEVOLVER_EXITO = 'OBTENER_LIBRO_DEVOLVER_EXITO';
export const LIBRO_DEVOLVER_ERROR = 'OBTENER_LIBRO_DEVOLVER_ERROR';

export const DESCARGA_PERSONALIBROS_EXITO = 'DESCARGA_PERSONALIBROS_EXITO';
export const DESCARGA_PERSONALIBROS_ERROR = 'DESCARGA_PERSONALIBROS_ERROR';
export const COMENZAR_DESCARGA_CATEGORIA = 'COMENZAR_DESCARGA_CATEGORIA';